<a href="https://colab.research.google.com/github/Ramandeep-Singh17/NumpyPracticeandNotes./blob/main/Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [217]:
import numpy as np# np aliyas short form, kuch bhi likh sakte jaruri nhi np


list se array

In [218]:
np.array([1,2,3,4,5])


array([1, 2, 3, 4, 5])

to save, array agar create hoga tu usmse array likha hua aayeaga

In [219]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [220]:
a=[1,2,3.5,"hello"]
a#print ke liye

[1, 2, 3.5, 'hello']

In [221]:
np.array(a)#list pass kar rhe hai


array(['1', '2', '3.5', 'hello'], dtype='<U32')

**Iska mtlb hai ki sare data types u32 mtlb string me convert ho gaye hai
** **Aagr hm string pass nhi kiye tu given example ke hisab se sab float ban jayega**

In [223]:
l=[[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Conversion of list to matrix.
 *2d array se uppper sab tensor hai isiliye tensor flow*

In [224]:
np.array(l)#Agar hm niche l likh de tu wo phirse list ke hisab se kaam karne lagega



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**`Array Generating function`**





In [225]:
np.arange(1,11)#1 se 10 tak generate ho jayega, ye range function hi hai but array ke liye isliye starting me "a".

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [226]:
arr=np.arange(1,11,2)# do ke gap me generate hoga.
arr#save karne ke liye

array([1, 3, 5, 7, 9])

In [227]:
# to genarte zeros
arr=np.zeros(6)
arr#yaha print ke liye arr kykui = karke

array([0., 0., 0., 0., 0., 0.])

In [161]:
#matrix of zeros
arr=np.zeros((4,8))
arr#yaha print ke liye arr kykui = karke

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [162]:
arr=np.ones((4,8))
arr

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

linspace or liner spacing. Return evenly spaced numbers over a specified interval.

In [163]:
arr= np.linspace(1,5,2)#hme 1 aur 5 ke bich me 2 number chahiye with equal space
arr

array([1., 5.])

In [164]:
arr= np.linspace(1,5,3)#hme 1 aur 5 ke bich me 3number chahiye with equal space
arr

array([1., 3., 5.])

In [165]:
arr= np.linspace(1,5,8)#hme 1 aur 5 ke bich me 8 number chahiye with equal space
arr

array([1.        , 1.57142857, 2.14285714, 2.71428571, 3.28571429,
       3.85714286, 4.42857143, 5.        ])

In [232]:
arr= np.linspace(1,10,100)#hme 1 aur 5 ke bich me 100 number chahiye with equal space
arr

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27


*RANDOM GENERATING FUNCTION*.  
 Ise hm random library with the help of rand function se banate hai.

In [167]:
np.random.rand(5)

array([0.94541066, 0.89359729, 0.96450944, 0.13637848, 0.16980317])

In [168]:
np.random.rand(20)# ye matrix nhi hai isme bas ek  hi [] agar do hota [[]] matrix hota hai sare value
#0-1 ke beach me ahi ye normalization hai
#agar standarization hoga tu value -3 se lekar +3 tak rahega


array([0.68006766, 0.49044431, 0.18750914, 0.72840741, 0.36001202,
       0.6961167 , 0.71996924, 0.03740479, 0.63318291, 0.68730421,
       0.62773053, 0.19829453, 0.03145609, 0.95862581, 0.37538663,
       0.95296957, 0.10501597, 0.0364164 , 0.39687689, 0.68697696])

In [169]:
np.random.randn(20)# agar hm randn likhe tu standarization value aayeagi
#agar standarization hoga tu value -3 se lekar +3 tak rahega


array([-0.86300943, -0.20791992,  0.01313673,  0.47555687, -0.01773264,
       -1.13991618, -0.65801802, -0.42939256,  1.88651976,  1.49510495,
        1.43359738,  0.76871394,  0.8177659 , -0.9451311 ,  0.2656231 ,
        0.39333288, -0.47557819,  1.25014834,  0.24446443, -0.24892363])

In [170]:
np.random.randint(10,20,5)#randint bata rha hai 10-20 ke beach me koi 5 random numbers and number repeat ho sakte hai.

array([18, 18, 17, 10, 11])

 **Array Attributes**
 attrubutes are variable defined inside a class
 methods are function defined insude a class

In [171]:
#attributes ko call nhi karte hai direct likhte hai but methods ko call karte hai.
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [172]:
arr.shape# shape attribute hai isme bracket nhi lagega agar lagaya tu galt ho jayeaga.


(3, 3)

In [173]:
arr.size

9

In [174]:
arr.dtype# data type ke jo integer hai.


dtype('int64')

**Array Methods**

In [175]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [176]:
arr.min()

np.int64(1)

In [177]:
arr.max()

np.int64(9)

In [178]:
arr.sum()

np.int64(45)

In [179]:
#row column sum karne ke liye
arr.sum(axis=0)#column sum


array([12, 15, 18])

In [180]:
arr.sum(axis=1)#row sum

array([ 6, 15, 24])

In [181]:
arr.mean()

np.float64(5.0)

In [182]:
arr.std()#standard deviation

np.float64(2.581988897471611)

In [183]:
arr.argmax()#Return highest index value which is 9 in thid case at 8 position starting from zero

np.int64(8)

**Reshaping and Resizing**

In [184]:
np.arange(1,31)#abhi ye call ho rha hai but store nhi

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [185]:
arr=np.arange(1,31)#abhi ye store  ho rha hai but call nhi

In [186]:
arr=np.arange(1,31)#abhi ye call ho rha hai and store bhi dono
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [187]:
arr=arr.reshape(6,5)#reshaping me dhyan dena hai ki element count bhi same hona chahiye warna nhi ho payeaga.
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [188]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

***NUMPY indexing and slicing of vectors***

In [189]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [190]:
arr[6]

np.int64(17)

In [191]:
arr[3:5]#slice ho gya

array([14, 15])

*NUMPY Indexing and slicing of a matrix*

In [192]:
arr= np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [193]:
arr[5]#for row

array([26, 27, 28, 29, 30])

In [194]:
arr[3]#for row

array([16, 17, 18, 19, 20])

In [195]:
arr[0,0]#for column

np.int64(1)

In [196]:
arr[5,4]#for column, pahle row then column

np.int64(30)

In [197]:
arr= np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [198]:
slice=arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [199]:
slice=arr[3:6,3:5]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [200]:
arr[:,2]#column slice

array([ 3,  8, 13, 18, 23, 28])

**Boolean indexing**

In [201]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [202]:
bool_index = arr%2 ==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [203]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

***Array opereations***

In [204]:
import numpy as np

In [205]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])
a2

array([ 6,  7,  8,  9, 10])

In [206]:
a1+a2#addition of two arrays

array([ 7,  9, 11, 13, 15])

In [207]:
a1=np.array([1,2,3,4,5,8])#add karne ke liye dono me same number of elemnts hone chahiye jo nhi hai
a2=np.array([6,7,8,9,10,8])#uuper 6 hai and niche 5 so ye nhi add hoga.So upper niche same rakhna chachiye agar add karna hai tu
a1+a2

array([ 7,  9, 11, 13, 15, 16])

In [208]:
a1=np.array([1,2,3,4,5,8])
a2=np.array([6,7,8,9,10,12])
arr2=a1+a2
arr2

array([ 7,  9, 11, 13, 15, 20])

In [209]:
a1-a2

array([-5, -5, -5, -5, -5, -4])

In [210]:
a1*a2

array([ 6, 14, 24, 36, 50, 96])

In [211]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ,
       0.66666667])

In [212]:
a1//a2#floor division

array([0, 0, 0, 0, 0, 0])

In [213]:
a1**a2

array([          1,         128,        6561,      262144,     9765625,
       68719476736])

**Broadcasting**

In [214]:
l=[10,20,30,40]
arr=np.array(l)

In [215]:
l+10# we cant directly add

TypeError: can only concatenate list (not "int") to list

In [ ]:
for i in l:# we need long procedure
  print (i+10)# to avoid this we directly add in array

In [ ]:
l=[10,20,30,40]#directly array me add karo ye hi broadcsting hai agar koi number hai jise add karna chahte ho sab me then  use broadcasting.
arr=np.array(l)
arr+10

In [ ]:
arr2=np.arange(1,26).reshape(5,5)
arr2

In [ ]:
# ab hm isme bhi broadcast kaar sakte hai
arr2=arr2+10

In [ ]:
arr2*2

**Deep and shallow copy**

In [ ]:
a=np.arange(1,21)
a

In [ ]:
slice=a[:5]
slice=slice*10
slice

In [ ]:
a#slice portion me change hone se array me change nhi hua hai but agar hm list use karte tu change hota .
# ye shallow copy hai  jisse main wale me change nhi ho rha hai
#but agar hm b=a likh ke a me change kare tu a me changaes hoga

**Matrix Operations**

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])


In [ ]:
A

In [ ]:
B

**Matrix multiplication**

In [ ]:
A*B# A and B multiply ho gya hai but wo matrix multiplication nhi hai.

In [ ]:
#tu hme matrix multiplication ke liye dot product karna hoga
A @ B #@ MATRIX MULTIPLICATION KAARTA HAI.

In [ ]:
#2nd method
np.dot(A,B)#Agar hm np.dot ka use kaare tu usse bhi ho jayega matrix multiplication.

**Transpose of a matrix**

In [ ]:
A

In [ ]:
A.T#.T for transpose

**Advanced Array opertaion**

In [ ]:
#stacking of two array we need to add vectors cant add matrix in stacking
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [ ]:
np.vstack((a,b))#verically stack

In [ ]:
np.hstack((a,b))#horixontal staack

In [ ]:
np.column_stack((a,b))#column stack

**Splitting Array**
*Array splitting need an equal division*

In [ ]:
c = np.arange(16).reshape(4, 4)
c

In [ ]:
np.hsplit(c,4)#horizontal split

In [ ]:

np.vsplit(c,2)# vertically split

In [ ]:
np.vsplit(c,3)# vertically split wrong divison for 16 array split does not result in an equal division

In [ ]:
a=np.vsplit (c,4)# vertically split
a

In [ ]:
for i in a :
  print (i)

**Practicce questions**

*Valid Sudoku*

In [ ]:
# row and column ka sum same hona chahiye and har block of 3x3 ka sum same hona chahiye
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [ ]:
b=np.sum(s,axis=1)# row kw liye 1 and column ke liye zero so valid sudoku
b==45# for true and false

In [ ]:
c=np.sum(s,axis=0)# so row and column are same it is valid
c==45

In [ ]:
s[0:3,0:3]

In [ ]:
s[0:3,3:6]

In [ ]:

s[0:3,6:9]

In [ ]:
#2nd approach we can use for loop
for i in range(0,9,3):
  for j in range(0,9,3):
    print(s[i:i+3,j:j+3])

In [ ]:
for i in range(0,9,3):
  for j in range(0,9,3):
    n= s[i:i+3,j:j+3]
    print (n.sum())

In [ ]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [ ]:

#Get the shape of the matrix.
data.shape

In [ ]:
#Find the average age of students.
np.mean(data[5:,0])# agar blank rahne doge tu bhi le lega kast tak
np.mean(data[:,0])# dono sahi hai

In [ ]:
#Extract Math marks of all students.
'''all rows are selected agar blank chode tu ye bhi comment hi hai'''
data[ :,1]

In [ ]:
#Find the highest Science mark.
data[ :,2]
np.max(data[ :,2])

In [ ]:
#Get details of the student who scored more than 90 in Math.
data[:,1]>90

In [ ]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1]>90]

In [ ]:
#Increase Math marks of all students by 5.
data[:,1]+5


In [ ]:
#Increase Math marks of all students by 5.
data[:,1]=data[:,1]+5
data

In [ ]:

#Find how many students are younger than 19.
data[:,0]<19

In [ ]:
#Find how many students are younger than 19.
len(data[data[:,0]<19])

In [ ]:
#Calculate the average marks in each subject (column-wise mean).
np.mean(data,axis=0)

In [ ]:
#Get data of students who scored at least 80 in both subjects.
data[data[:,1]>80& (data[:,2]>80)]


In [ ]:
#Replace all Science marks < 75 with 0.
data[data[:,2]<75,2]=0#[ pahle row and then column is selected]
data