<a href="https://colab.research.google.com/github/Ramandeep-Singh17/NumpyPracticeandNotes./blob/main/Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [77]:
import numpy as np# np aliyas short form, kuch bhi likh sakte jaruri nhi np


list se array

In [78]:
np.array([1,2,3,4,5])


array([1, 2, 3, 4, 5])

to save, array agar create hoga tu usmse array likha hua aayeaga

In [79]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [80]:
a=[1,2,3.5,"hello"]
a  #print ke liye agar a nhi likhenge tu print nhi karega

[1, 2, 3.5, 'hello']

In [81]:
np.array(a)#list pass kar rhe hai


array(['1', '2', '3.5', 'hello'], dtype='<U32')

**Iska mtlb hai ki sare data types u32 mtlb string me convert ho gaye hai
** **Aagr hm string pass nhi kiye tu given example ke hisab se sab float ban jayega**

In [82]:
l=[[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Conversion of list to matrix.
 *2d array se uppper sab tensor hai isiliye tensor flow*

In [83]:
np.array(l)#Agar hm niche l likh de tu wo phirse list ke hisab se kaam karne lagega



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**`Array Generating function`**





In [84]:
np.arange(1,11)#1 se 10 tak generate ho jayega, ye range function hi hai but array ke liye isliye starting me "a".

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [85]:
arr=np.arange(1,11,2)# do ke gap me generate hoga.
arr#save karne ke liye

array([1, 3, 5, 7, 9])

In [86]:
# to genarte zeros
arr=np.zeros(6)
arr#yaha print ke liye arr kykui = karke

array([0., 0., 0., 0., 0., 0.])

In [87]:
#matrix of zeros
arr=np.zeros((4,8))
arr#yaha print ke liye arr kykui = karke

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [88]:
arr=np.ones((4,8))
arr

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

linspace or liner spacing. Return evenly spaced numbers over a specified interval.

In [89]:
arr= np.linspace(1,5,2)#hme 1 aur 5 ke bich me 2 number chahiye with equal space
arr

array([1., 5.])

In [90]:
arr= np.linspace(1,5,3)#hme 1 aur 5 ke bich me 3number chahiye with equal space
arr

array([1., 3., 5.])

In [91]:
arr= np.linspace(1,5,8)#hme 1 aur 5 ke bich me 8 number chahiye with equal space
arr

array([1.        , 1.57142857, 2.14285714, 2.71428571, 3.28571429,
       3.85714286, 4.42857143, 5.        ])

In [92]:
arr= np.linspace(1,10,100)#hme 1 aur 5 ke bich me 100 number chahiye with equal space
arr

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27


*RANDOM GENERATING FUNCTION*.  
 Ise hm random library with the help of rand function se banate hai.

In [93]:
np.random.rand(5)

array([0.17205104, 0.31324745, 0.48448622, 0.754382  , 0.76792879])

In [94]:
np.random.rand(20)# ye matrix nhi hai isme bas ek  hi [] agar do hota [[]] matrix hota hai sare value
#0-1 ke beach me ahi ye normalization hai
#agar standarization hoga tu value -3 se lekar +3 tak rahega


array([0.27324853, 0.09114899, 0.48968063, 0.0712548 , 0.4077626 ,
       0.89999117, 0.55768355, 0.15722741, 0.64971521, 0.57679824,
       0.53952377, 0.50098442, 0.50282708, 0.14425576, 0.62554562,
       0.14918426, 0.0411854 , 0.102285  , 0.45865921, 0.74034025])

In [95]:
np.random.randn(20)# agar hm randn likhe tu standarization value aayeagi
#agar standarization hoga tu value -3 se lekar +3 tak rahega


array([ 1.16987972,  0.09421405,  0.22271839,  0.8363208 , -1.27006872,
       -0.54070012, -0.89793492,  1.45432686,  1.99721658,  0.08519317,
       -0.55978834,  0.47881387,  1.01265748, -0.92388936, -1.16406174,
       -0.47813229, -0.01111456,  0.80556521, -0.60006135,  0.07445483])

In [96]:
np.random.randint(10,20,5)#randint bata rha hai 10-20 ke beach me koi 5 random numbers and number repeat ho sakte hai.

array([12, 16, 11, 16, 19])

 **Array Attributes**
 attrubutes are variable defined inside a class
 methods are function defined insude a class

In [97]:
#attributes ko call nhi karte hai direct likhte hai but methods ko call karte hai.
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [98]:
arr.shape# shape attribute hai isme bracket nhi lagega agar lagaya tu galt ho jayeaga.


(3, 3)

In [99]:
arr.size

9

In [100]:
arr.dtype# data type ke jo integer hai.


dtype('int64')

**Array Methods**

In [101]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [102]:
arr.min()

np.int64(1)

In [103]:
arr.max()

np.int64(9)

In [104]:
arr.sum()

np.int64(45)

In [105]:
#row column sum karne ke liye
arr.sum(axis=0)#column sum


array([12, 15, 18])

In [106]:
arr.sum(axis=1)#row sum

array([ 6, 15, 24])

In [107]:
arr.mean()

np.float64(5.0)

In [108]:
arr.std()#standard deviation

np.float64(2.581988897471611)

In [109]:
arr.argmax()#Return highest index value which is 9 in thid case at 8 position starting from zero

np.int64(8)

**Reshaping and Resizing**

In [110]:
np.arange(1,31)#abhi ye call ho rha hai but store nhi

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [111]:
arr=np.arange(1,31)#abhi ye store  ho rha hai but call nhi

In [112]:
arr=np.arange(1,31)#abhi ye call ho rha hai and store bhi dono
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [113]:
arr=arr.reshape(6,5)#reshaping me dhyan dena hai ki element count bhi same hona chahiye warna nhi ho payeaga.
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [114]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

***NUMPY indexing and slicing of vectors***

In [115]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [116]:
arr[6]

np.int64(17)

In [117]:
arr[3:5]#slice ho gya

array([14, 15])

*NUMPY Indexing and slicing of a matrix*

In [118]:
arr= np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [119]:
arr[5]#for row

array([26, 27, 28, 29, 30])

In [120]:
arr[3]#for row

array([16, 17, 18, 19, 20])

In [121]:
arr[0,0]#for column

np.int64(1)

In [122]:
arr[5,4]#for column, pahle row then column

np.int64(30)

In [123]:
arr= np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [124]:
slice=arr[0:2,1:3]#ye dikha rha hai ki row no 0 se leke 2 tak chalega but 2 include  nhi hoga
# and 1:3 ka mtlb hai ki column 1 se leke 3 tak karenege but 3 ko nhi
slice

array([[2, 3],
       [7, 8]])

In [125]:
slice=arr[3:6,3:5]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [126]:
arr[:,2]#column slice

array([ 3,  8, 13, 18, 23, 28])

**Boolean indexing**

In [127]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [128]:
bool_index = arr%2 ==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [129]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

***Array opereations***

In [130]:
import numpy as np

In [131]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])
a2

array([ 6,  7,  8,  9, 10])

In [132]:
a1+a2#addition of two arrays

array([ 7,  9, 11, 13, 15])

In [194]:
a1=np.array([1,2,3,4,5,6])#add karne ke liye dono me same number of elemnts hone chahiye jo nhi hai
a2=np.array([6,7,8,9,10])#uuper 6 hai and niche 5 so ye nhi add hoga.So upper niche same rakhna chachiye agar add karna hai tu
a1+a2

ValueError: operands could not be broadcast together with shapes (6,) (5,) 

In [195]:
a1=np.array([1,2,3,4,5,8])
a2=np.array([6,7,8,9,10,12])
arr2=a1+a2
arr2

array([ 7,  9, 11, 13, 15, 20])

In [135]:
a1-a2

array([-5, -5, -5, -5, -5, -4])

In [136]:
a1*a2

array([ 6, 14, 24, 36, 50, 96])

In [137]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ,
       0.66666667])

In [138]:
a1//a2#floor division

array([0, 0, 0, 0, 0, 0])

In [139]:
a1**a2

array([          1,         128,        6561,      262144,     9765625,
       68719476736])

**Broadcasting**

In [196]:
l=[10,20,30,40]
arr=np.array(l)

In [197]:
l+10# we cant directly add

TypeError: can only concatenate list (not "int") to list

In [144]:
for i in l:# we need long procedure
  print (i+10)# to avoid this we directly add in array

20
30
40
50


In [198]:
l=[10,20,30,40]#directly array me add karo ye hi broadcsting hai agar koi number hai jise add karna chahte ho sab me then  use broadcasting.
arr=np.array(l)
arr+10

array([20, 30, 40, 50])

In [146]:
arr2=np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [147]:
# ab hm isme bhi broadcast kaar sakte hai
arr2=arr2+10

In [149]:
arr2*2

array([[22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50],
       [52, 54, 56, 58, 60],
       [62, 64, 66, 68, 70]])

**Deep and shallow copy**

In [200]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [201]:
slice=a[:5]
slice=slice*10
slice

array([10, 20, 30, 40, 50])

In [152]:
a#slice portion me change hone se array me change nhi hua hai but agar hm list use karte tu change hota .
# ye shallow copy hai  jisse main wale me change nhi ho rha hai
#but agar hm b=a likh ke a me change kare tu a me changaes hoga

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [202]:
#shallow copy me change karne se original (main) array me bhi change hota hai.
# Deep copy me change karne se original me change nhi hot hai.

**Matrix Operations**

In [153]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])


In [154]:
A

array([[1, 2],
       [3, 4]])

In [155]:
B

array([[5, 6],
       [7, 8]])

**Matrix multiplication**

In [203]:
A*B# A and B multiply ho gya hai but wo matrix multiplication nhi hai.

array([[ 5, 12],
       [21, 32]])

In [204]:
#tu hme matrix multiplication ke liye dot product karna hoga
A @ B #@ MATRIX MULTIPLICATION KAARTA HAI.

array([[19, 22],
       [43, 50]])

In [205]:
#2nd method
np.dot(A,B)#Agar hm np.dot ka use kaare tu usse bhi ho jayega matrix multiplication.

array([[19, 22],
       [43, 50]])

**Transpose of a matrix**

In [159]:
A

array([[1, 2],
       [3, 4]])

In [160]:
A.T#.T for transpose

array([[1, 3],
       [2, 4]])

**Advanced Array opertaion**

In [206]:
#stacking of two array we need to add vectors cant add matrix in stacking
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [207]:
np.vstack((a,b))#verically stack

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [209]:
np.hstack((a,b))#horixontal staack

array([1, 2, 3, 4, 5, 6, 7, 8])

In [164]:
np.column_stack((a,b))#column stack

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

**Splitting Array**
*Array splitting need an equal division*

In [211]:
c = np.arange(16).reshape(4, 4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [215]:
np.hsplit(c,4)#horizontal split

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [167]:

np.vsplit(c,2)# vertically split

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [168]:
np.vsplit(c,3)# vertically split wrong divison for 16 array split does not result in an equal division

ValueError: array split does not result in an equal division

In [216]:
a=np.vsplit (c,4)# vertically split
a

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [170]:
for i in a :
  print (i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]


**Practicce questions**

*Valid Sudoku*

In [171]:
# row and column ka sum same hona chahiye and har block of 3x3 ka sum same hona chahiye
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [172]:
b=np.sum(s,axis=1)# row kw liye 1 and column ke liye zero so valid sudoku
b==45# for true and false

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [173]:
c=np.sum(s,axis=0)# so row and column are same it is valid
c==45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [174]:
s[0:3,0:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [175]:
s[0:3,3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [176]:

s[0:3,6:9]

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [177]:
#2nd approach we can use for loop
for i in range(0,9,3):
  for j in range(0,9,3):
    print(s[i:i+3,j:j+3])

[[5 3 4]
 [6 7 2]
 [1 9 8]]
[[6 7 8]
 [1 9 5]
 [3 4 2]]
[[9 1 2]
 [3 4 8]
 [5 6 7]]
[[8 5 9]
 [4 2 6]
 [7 1 3]]
[[7 6 1]
 [8 5 3]
 [9 2 4]]
[[4 2 3]
 [7 9 1]
 [8 5 6]]
[[9 6 1]
 [2 8 7]
 [3 4 5]]
[[5 3 7]
 [4 1 9]
 [2 8 6]]
[[2 8 4]
 [6 3 5]
 [1 7 9]]


In [178]:
for i in range(0,9,3):
  for j in range(0,9,3):
    n= s[i:i+3,j:j+3]
    print (n.sum())

45
45
45
45
45
45
45
45
45


In [179]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [180]:

#Get the shape of the matrix.
data.shape

(5, 3)

In [181]:
#Find the average age of students.
np.mean(data[5:,0])# agar blank rahne doge tu bhi le lega kast tak
np.mean(data[:,0])# dono sahi hai

/usr/local/lib/python3.11/dist-packages/numpy/_core/fromnumeric.py:3596: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.11/dist-packages/numpy/_core/_methods.py:138: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)


np.float64(18.4)

In [182]:
#Extract Math marks of all students.
'''all rows are selected agar blank chode tu ye bhi comment hi hai'''
data[ :,1]

array([85, 92, 76, 65, 90])

In [183]:
#Find the highest Science mark.
data[ :,2]
np.max(data[ :,2])

np.int64(95)

In [184]:
#Get details of the student who scored more than 90 in Math.
data[:,1]>90

array([False,  True, False, False, False])

In [185]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1]>90]

array([[19, 92, 88]])

In [186]:
#Increase Math marks of all students by 5.
data[:,1]+5


array([90, 97, 81, 70, 95])

In [187]:
#Increase Math marks of all students by 5.
data[:,1]=data[:,1]+5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [188]:

#Find how many students are younger than 19.
data[:,0]<19

array([ True, False,  True,  True, False])

In [189]:
#Find how many students are younger than 19.
len(data[data[:,0]<19])

3

In [190]:
#Calculate the average marks in each subject (column-wise mean).
np.mean(data,axis=0)

array([18.4, 86.6, 83.2])

In [191]:
#Get data of students who scored at least 80 in both subjects.
data[data[:,1]>80& (data[:,2]>80)]


array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [192]:
#Replace all Science marks < 75 with 0.
data[data[:,2]<75,2]=0#[ pahle row and then column is selected]
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])