<a href="https://colab.research.google.com/github/Ramandeep-Singh17/NumpyPracticeandNotes./blob/main/Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np# np aliyas short form, kuch bhi likh sakte jaruri nhi np


list se array

In [4]:
np.array([1,2,3,4,5])


array([1, 2, 3, 4, 5])

to save, array agar create hoga tu usmse array likha hua aayeaga

In [6]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [7]:
a=[1,2,3.5,"hello"]
a#print ke liye

[1, 2, 3.5, 'hello']

In [8]:
np.array(a)#list pass kar rhe hai


array(['1', '2', '3.5', 'hello'], dtype='<U32')

**Iska mtlb hai ki sare data types u32 mtlb string me convert ho gaye hai
** **Aagr hm string pass nhi kiye tu given example ke hisab se sab float ban jayega**

In [9]:
l=[[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Conversion of list to matrix.
 *2d matrix se uppper sab tensor hai isiliye tensor flow*

In [12]:
np.array(l)#Agar hm niche l likh de tu wo phirse list ke hisab se kaam karne lagega



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**`Array Generating function`**





In [14]:
np.arange(1,11)#1 se 10 tak generate ho jayega, ye range function hi hai but array ke liye isliye starting me "a".

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
np.arange(1,11,2)# do ke gap me generate hoga.
arr#save karne ke liye

array([1, 3, 5, 7, 9])

In [22]:
# to genarte zeros
arr=np.zeros(6)
arr#yaha print ke liye arr kykui = karke

array([0., 0., 0., 0., 0., 0.])

In [24]:
#matrix of zeros
arr=np.zeros((4,8))
arr#yaha print ke liye arr kykui = karke

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [26]:
arr=np.ones((4,8))
arr

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

linspace or liner spacing. Return evenly spaced numbers over a specified interval.

In [27]:
arr= np.linspace(1,5,2)#hme 1 aur 5 ke bich me 2 number chahiye with equal space
arr

array([1., 5.])

In [29]:
arr= np.linspace(1,5,3)#hme 1 aur 5 ke bich me 3number chahiye with equal space
arr

array([1., 3., 5.])

In [30]:
arr= np.linspace(1,5,8)#hme 1 aur 5 ke bich me 8 number chahiye with equal space
arr

array([1.        , 1.57142857, 2.14285714, 2.71428571, 3.28571429,
       3.85714286, 4.42857143, 5.        ])

In [34]:
arr= np.linspace(1,5,100)#hme 1 aur 5 ke bich me 200 number chahiye with equal space
arr

array([1.        , 1.04040404, 1.08080808, 1.12121212, 1.16161616,
       1.2020202 , 1.24242424, 1.28282828, 1.32323232, 1.36363636,
       1.4040404 , 1.44444444, 1.48484848, 1.52525253, 1.56565657,
       1.60606061, 1.64646465, 1.68686869, 1.72727273, 1.76767677,
       1.80808081, 1.84848485, 1.88888889, 1.92929293, 1.96969697,
       2.01010101, 2.05050505, 2.09090909, 2.13131313, 2.17171717,
       2.21212121, 2.25252525, 2.29292929, 2.33333333, 2.37373737,
       2.41414141, 2.45454545, 2.49494949, 2.53535354, 2.57575758,
       2.61616162, 2.65656566, 2.6969697 , 2.73737374, 2.77777778,
       2.81818182, 2.85858586, 2.8989899 , 2.93939394, 2.97979798,
       3.02020202, 3.06060606, 3.1010101 , 3.14141414, 3.18181818,
       3.22222222, 3.26262626, 3.3030303 , 3.34343434, 3.38383838,
       3.42424242, 3.46464646, 3.50505051, 3.54545455, 3.58585859,
       3.62626263, 3.66666667, 3.70707071, 3.74747475, 3.78787879,
       3.82828283, 3.86868687, 3.90909091, 3.94949495, 3.98989


*RANDOM GENERATING FUNCTION*.  
 Ise hm random library with the help of rand function se banate hai.

In [35]:
np.random.rand(5)

array([0.71152882, 0.25649058, 0.93809383, 0.60625823, 0.62932669])

In [38]:
np.random.rand(20)# ye matrix nhi hai isme bas ek  hi [] agar do hota [[]] matrix hota hai sare value
#0-1 ke beach me ahi ye normalization hai
#agar standarization hoga tu value -3 se lekar +3 tak rahega


array([0.14710032, 0.99323879, 0.69508785, 0.27772915, 0.58231427,
       0.94266898, 0.83106925, 0.52134774, 0.46836664, 0.78229351,
       0.62194064, 0.05819361, 0.74398479, 0.25425406, 0.65637682,
       0.93332617, 0.78651695, 0.74991527, 0.62409086, 0.29854828])

In [41]:
np.random.randn(20)# agar hm randn likhe tu standarization value aayeagi
#agar standarization hoga tu value -3 se lekar +3 tak rahega


array([-0.36165738, -0.296148  , -1.60258897,  2.79120336, -0.67391217,
       -0.32446556,  1.44887206,  0.90513584, -0.06570972, -0.01325286,
        1.50204976, -1.59557541,  0.59296069, -0.69223315, -1.40297462,
       -0.85979667,  1.17795705, -0.22261673, -1.26198423, -0.60194474])

In [47]:
np.random.randint(10,20,5)#randint bata rha hai 10-20 ke beach me koi 5 random numbers and number repeat ho sakte hai.

array([19, 15, 17, 16, 18])

 **Array Attributes**
 attrubutes are variable defined inside a class
 methods are function defined insude a class

In [50]:
#attributes ko call nhi karte hai direct likhte hai but methods ko call karte hai.
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
arr.shape# shape attribute hai isme bracket nhi lagega agar lagaya tu galt ho jayeaga.


(3, 3)

In [53]:
arr.size

9

In [55]:
arr.dtype# data type ke jo integer hai.


dtype('int64')

**Array Methods**

In [58]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
arr.min()

np.int64(1)

In [60]:
arr.max()

np.int64(9)

In [61]:
arr.sum()

np.int64(45)

In [62]:
#row column sum karne ke liye
arr.sum(axis=0)#column sum


array([12, 15, 18])

In [63]:
arr.sum(axis=1)#row sum

array([ 6, 15, 24])

In [65]:
arr.mean()

np.float64(5.0)

In [66]:
arr.std()#standard deviation

np.float64(2.581988897471611)

In [68]:
arr.argmax()#Return highest index value which is 9 in thid case at 8 position starting from zero

np.int64(8)

**Reshaping and Resizing**

In [69]:
np.arange(1,31)#abhi ye call ho rha hai but store nhi

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [70]:
arr=np.arange(1,31)#abhi ye store  ho rha hai but call nhi

In [79]:
arr=np.arange(1,31)#abhi ye call ho rha hai and store bhi dono
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [84]:
arr=arr.reshape(6,5)#reshaping me dhyan dena hai ki element count bhi same hona chahiye warna nhi ho payeaga.
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [85]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

***NUMPY indexing and slicing of vectors***

In [3]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
arr[6]

np.int64(17)

In [8]:
arr[3:5]#slice ho gya

array([14, 15])

*NUMPY Indexing and slicing of a matrix*

In [9]:
arr= np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [11]:
arr[5]#for row

array([26, 27, 28, 29, 30])

In [12]:
arr[3]#for row

array([16, 17, 18, 19, 20])

In [13]:
arr[0,0]#for column

np.int64(1)

In [14]:
arr[5,4]#for column, pahle row then column

np.int64(30)

In [16]:
arr= np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [17]:
slice=arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [19]:
slice=arr[3:6,3:5]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [21]:
arr[:,2]#column slice

array([ 3,  8, 13, 18, 23, 28])

**Boolean indexing**

In [22]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [28]:
bool_index = arr%2 ==0
bool_index

array([ True,  True,  True,  True,  True])

In [29]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

***Array opereations***

In [2]:
import numpy as np

In [4]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])
a2

array([ 6,  7,  8,  9, 10])

In [6]:
a1+a2#addition of two arrays

array([ 7,  9, 11, 13, 15])

In [7]:
a1=np.array([1,2,3,4,5,8])#add karne ke liye dono me same number of elemnts hone chahiye jo nhi hai
a2=np.array([6,7,8,9,10])#uuper 6 hai and niche 5 so ye nhi add hoga.
a1+a2

ValueError: operands could not be broadcast together with shapes (6,) (5,) 

In [12]:
a1=np.array([1,2,3,4,5,8])
a2=np.array([6,7,8,9,10,12])
arr2=a1+a2
arr2

array([ 7,  9, 11, 13, 15, 20])

In [13]:
a1-a2

array([-5, -5, -5, -5, -5, -4])

In [14]:
a1*a2

array([ 6, 14, 24, 36, 50, 96])

In [15]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ,
       0.66666667])

In [16]:
a1//a2#floor division

array([0, 0, 0, 0, 0, 0])

In [17]:
a1**a2

array([          1,         128,        6561,      262144,     9765625,
       68719476736])

**Broadcasting**

In [23]:
l=[10,20,30,40]
arr=np.array(l)

In [20]:
l+10# we cant directly add

TypeError: can only concatenate list (not "int") to list

In [25]:
for i in l:# we need long procedure
  print (i+10)# to avoid this we directly add in array

20
30
40
50


In [27]:
l=[10,20,30,40]#directly array me add karo ye hi broadcsting hai agar koi number hai jise add karna chahte ho sab me then  use broadcasting.
arr=np.array(l)
arr+10

array([20, 30, 40, 50])

In [32]:
arr2=np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [34]:
# ab hm isme bhi broadcast kaar sakte hai
arr2=arr2+10

In [35]:
arr2*2

array([[22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50],
       [52, 54, 56, 58, 60],
       [62, 64, 66, 68, 70]])

**Deep and shallow copy**

In [36]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [40]:
slice=a[:5]
slice=slice*10
slice

array([10, 20, 30, 40, 50])

In [41]:
a#slice portion me change hone se array me change nhi hua hai but agar hm list use karte tu change hota .
# ye shallow copy hai  jisse main wale me change nhi ho rha hai
#but agar hm b=a likh ke a me change kare tu a me changaes hoga

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

**Matrix Operations**

In [42]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])


In [44]:
A

array([[1, 2],
       [3, 4]])

In [45]:
B

array([[5, 6],
       [7, 8]])

**Matrix multiplication**

In [47]:
A*B# A and B multiply ho gya hai but wo matrix multiplication nhi hai.

array([[ 5, 12],
       [21, 32]])

In [49]:
#tu hme matrix multiplication ke liye dot product karna hoga
A @ B #@ MATRIX MULTIPLICATION KAARTA HAI.

array([[19, 22],
       [43, 50]])

In [51]:
#2nd method
np.dot(A,B)#Agar hm np.dot ka use kaare tu usse bhi ho jayega matrix multiplication.

array([[19, 22],
       [43, 50]])

**Transpose of a matrix**

In [52]:
A

array([[1, 2],
       [3, 4]])

In [54]:
A.T#.T for transpose

array([[1, 3],
       [2, 4]])

**Advanced Array opertaion**

In [55]:
#stacking of two array we need to add vectors cant add matrix in stacking
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [56]:
np.vstack((a,b))#verically stack

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [57]:
np.hstack((a,b))#horixontal staack

array([1, 2, 3, 4, 5, 6, 7, 8])

In [58]:
np.column_stack((a,b))#column stack

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

**Splitting Array**
*Array splitting need an equal division*

In [4]:
c = np.arange(16).reshape(4, 4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [5]:
np.hsplit(c,4)#horizontal split

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [6]:
np.vsplit(c,2)# vertically split

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [8]:
np.vsplit(c,3)# vertically split wrong divison for 16 array split does not result in an equal division

ValueError: array split does not result in an equal division

In [10]:
a=np.vsplit (c,4)# vertically split
a

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [11]:
for i in a :
  print (i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]


**Practicce questions**

*Valid Sudoku*

In [21]:
# row and column ka sum same hona chahiye and har block of 3x3 ka sum same hona chahiye
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [30]:
b=np.sum(s,axis=1)# row kw liye 1 and column ke liye zero so valid sudoku
b==45# for true and false

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [33]:
c=np.sum(s,axis=0)# so row and column are same it is valid
c==45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [34]:
s[0:3,0:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [35]:
s[0:3,3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [36]:
s[0:3,6:9]

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [37]:
#2nd approach we can use for loop
for i in range(0,9,3):
  for j in range(0,9,3):
    print(s[i:i+3,j:j+3])

[[5 3 4]
 [6 7 2]
 [1 9 8]]
[[6 7 8]
 [1 9 5]
 [3 4 2]]
[[9 1 2]
 [3 4 8]
 [5 6 7]]
[[8 5 9]
 [4 2 6]
 [7 1 3]]
[[7 6 1]
 [8 5 3]
 [9 2 4]]
[[4 2 3]
 [7 9 1]
 [8 5 6]]
[[9 6 1]
 [2 8 7]
 [3 4 5]]
[[5 3 7]
 [4 1 9]
 [2 8 6]]
[[2 8 4]
 [6 3 5]
 [1 7 9]]


In [42]:
for i in range(0,9,3):
  for j in range(0,9,3):
    n= s[i:i+3,j:j+3]
    print (n.sum())

45
45
45
45
45
45
45
45
45


In [89]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [90]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [92]:
#Find the average age of students.
np.mean(data[5:,0])# agar blank rahne doge tu bhi le lega kast tak
np.mean(data[:,0])# dono sahi hai

np.float64(18.4)

In [93]:
#Extract Math marks of all students.
'''all rows are selected agar blank chode tu ye bhi comment hi hai'''
data[ :,1]

array([85, 92, 76, 65, 90])

In [94]:
#Find the highest Science mark.
data[ :,2]
np.max(data[ :,2])

np.int64(95)

In [95]:
#Get details of the student who scored more than 90 in Math.
data[:,1]>90

array([False,  True, False, False, False])

In [96]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1]>90]

array([[19, 92, 88]])

In [97]:
#Increase Math marks of all students by 5.
data[:,1]+5


array([90, 97, 81, 70, 95])

In [98]:
#Increase Math marks of all students by 5.
data[:,1]=data[:,1]+5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [99]:
#Find how many students are younger than 19.
data[:,0]<19

array([ True, False,  True,  True, False])

In [100]:
#Find how many students are younger than 19.
len(data[data[:,0]<19])

3

In [101]:
#Calculate the average marks in each subject (column-wise mean).
np.mean(data,axis=0)

array([18.4, 86.6, 83.2])

In [104]:
#Get data of students who scored at least 80 in both subjects.
data[data[:,1]>80& (data[:,2]>80)]


array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [105]:
#Replace all Science marks < 75 with 0.
data[data[:,2]<75,2]=0#[ pahle row and then column is selected]
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])